#include <iostream>
#include <cstdint>

constexpr uint32_t state_len = 624;

struct STATE
{
  uint32_t index;
  uint32_t MT[2 * state_len];
};

STATE state;

inline void init_state(uint32_t seed)
{
  state.MT[0] = seed;
  for (uint32_t i = 1; i < state_len; ++i)
    state.MT[i] = i + 0x6C078965 * (state.MT[i-1] ^ (state.MT[i-1] >> 30));

  state.index = 0x270;
}

inline void twist()
{
  for (uint32_t i = 0; i < state_len; ++i)
  {
    uint32_t y = state.MT[i];
    uint32_t next =  state.MT[i+1];
    y ^= next;
    y &= 0x7FFFFFFF;
    y ^= state.MT[i];

    uint32_t mask = y & 1;
    mask = mask % 2 == 1 ? 0xFFFFFFFF : 0;

    y >>= 1;
    mask &= 0x9908B0DF;
    uint32_t xor_val = state.MT[i + 397];
    mask ^= xor_val;
    y ^= mask;
    state.MT[i + state_len] = y;
  }
}

inline uint32_t get_number()
{
  if (state.index == 0x270)
    twist();

  uint32_t y = state.MT[state.index];
  state.index ++;

  y = y ^ (y >> 11);
  y = y ^ ((y & 0xFF3A58AD) << 7);
  y = y ^ ((y & 0xFFFFDF8C) << 15);
  y = y ^ (y >> 18);

  return y;
}

// this function will check if two values satisfy the opaque predicate from the crackme
inline bool vals_pass(uint32_t val1, uint32_t val2)
{
  uint32_t res1 = val1 & val2;

  uint32_t res2 = val1 & val2;
  res2 -= val2;
  res2 &= val2;
  res2 &= val2;
  res2 -= 1;
  res2 &= val2;

  //printf("%08x\n%08x\n\n", res1, res2);
  return res1 != res2;
}

// this function checks if the first two values generated by a given seed satisfy the opaque predicate
inline void check_seed(uint32_t seed)
{
  init_state(seed);

  uint32_t first = get_number();
  uint32_t second = get_number();

  if (vals_pass(first, second))
    printf("Passed: %08x\n", seed);
}

int main()
{
  // we loop over all possible seeds and check if the first three generated values satisfy the conditions from the crackme
  uint32_t seed = 0;
  do
  {
    init_state(seed);
    if (get_number() == 0x45CFB9C4
      && get_number() == 0x619BB736
      && get_number() == 0x11636892)
      printf("%08x\n", seed);

    ++seed;
  } while (seed != 0); // if seed == 0 at the end of the loop the there was an overflow => we checked all possible values

  return 0;
}